### ISSUE TITLE
Add issue labels for the repository

### ISSUE THREAD

**Issue by ristomatti** [node-lifx/lifx-lan-client#13]
As it's possible this repository will start seeing more bug reports but also questions, feature requests etc., it'd be nice if they would be labeled as such. I would add them myself if I had the required access rights. :)

**Comment by Sawtaytoes** [comment]
Ok, I think I figured out how to give you access. See if that works :).

**Comment by Sawtaytoes** [comment]
Are your access permissions working now?

**Comment by ristomatti** [comment]
Sorry I managed to forget to check. I've ended being most of my vacation off the computer. At least it seems I can assign labels now (quickly tried on my phone). Thanks! I'll close this.
