### ISSUE TITLE
[Feature Request] add support for LIFX Switch

### ISSUE THREAD

**Issue by lebowski9000** [node-lifx/lifx-lan-client#38]
Any chance to get support for the LIFX Switch?

**Comment by Shakesbeard** [comment]
That is easy going actually but the protocol is not fully released, yet. Only basic on off toggling is support at the moment.
There is a lot more to come for switches. I dunno if the primary maintainer here would want to start implementing it already or wait for the full set of features.

**Comment by ristomatti** [comment]
Background note: I asked to submit an issue here as it was first reported at https://github.com/ristomatti/node-red-contrib-node-lifx/issues/8 but would need to be implemented for lifx-lan-client first. Like I've commented on the linked issue, I currently don't have the time to try this... Especially as the switches are not even available here nor something I could reasonably install on a rental apartment.

Would you want to give it a shot based on the spec or should we just add a "help wanted" label which is what I promised to at least do? 🙂

**Comment by ristomatti** [comment]
It sounds like you're better up to date on this. I haven't even looked at the specs given the reasons above.

**Comment by Shakesbeard** [comment]
I don't know whether the info I got falls under IP. But I guess it is legal to say that there will be different models of the switch device and they will get more features than just on/off.

**Comment by ristomatti** [comment]
Well, I'd say it'd be the only logical step after testing the markets to add new features so it cannot be too confidential.

Considering the API - the way they've designed their API's in the past has been to add features on top of the previous API's while still maintaining compatibility. I'd expect the light switch API's to follow a similar pattern. And even if the future products would use a different API, I doubt they'd break compatibility for the first line of switch-type products. 

With this line of thought I wouldn't be worried about it being wasted effort to add support at this point if someone is willing to take the challenge. :crossed_fingers:

**Comment by Shakesbeard** [comment]
So I shipwrecked my repo and I have not found the nerve to fix it yet.
But maybe this helps and maybe someone can integrate it if interrested.

And no, I have not implemented any tests or wrapper functions on the device either. I am handling this on app level for my purposes at the moment.

Notable is that the max. number of relays is 4 with zero based index. Set power only supports 0 or max value (think it was 65535) at the moment.

**packet.js Additions**
```
{ id: 816, name: 'getRelayPower' }, { id: 817, name: 'setRelayPower' }, { id: 818, name: 'stateRelayPower' }
```
**getRelayPower.js**
```
'use strict';

var Packet = {
  size: 1
};

/**
 * Converts the given packet specific object into a packet
 * @param  {Object} obj object with configuration data
 * @param  {Number} obj.relayIndex start zone index, between 0 and 255
 * @return {Buffer} packet
 */
Packet.toBuffer = function (obj) {
  var buf = Buffer.alloc(this.size);
  buf.fill(0);
  var offset = 0;

  if (typeof obj.relayIndex !== 'number' && obj.relayIndex < 0 || obj.relayIndex > 3) {
    throw new RangeError('Invalid relayIndex value given for getRelayPower LIFX packet, must be a number between 0 and 3');
  }
  buf.writeUInt8(obj.relayIndex, offset);
  offset += 1;
  
  return buf;
};

module.exports = Packet;

```
**setRelayPower.js**
```
'use strict';

var Packet = {
  size: 3
};

/**
 * Converts packet specific data from a buffer to an object
 * @param  {Buffer} buf Buffer containing only packet specific data no header
 * @return {Object}     Information contained in packet
 */
Packet.toObject = function (buf) {
  var obj = {};
  var offset = 0;

  if (buf.length !== this.size) {
    throw new Error('Invalid length given for stateRelayPower LIFX packet');
  }

  obj = {};
  obj.relayIndex = buf.readUInt8LE(offset);
  offset += 1;
  obj.relayLevel = buf.readUInt16LE(offset);
  offset += 2;

  return obj;
};

/**
 * Converts the given packet specific object into a packet
 * @param  {Object} obj object with configuration data
 * @return {Buffer}     packet
 */
Packet.toBuffer = function (obj) {
  var buf = Buffer.alloc(this.size);
  buf.fill(0);
  var offset = 0;

  buf.readUInt8LE(obj.relayIndex, offset);
  offset += 1;
  buf.writeUInt16LE(obj.relayLevel, offset);
  offset += 2;

  return buf;
};

module.exports = Packet;

```
**stateRelayPower.js**
```
'use strict';

var Packet = {
  size: 3
};

/**
 * Converts packet specific data from a buffer to an object
 * @param  {Buffer} buf Buffer containing only packet specific data no header
 * @return {Object}     Information contained in packet
 */
Packet.toObject = function (buf) {
  var obj = {};
  var offset = 0;

  if (buf.length !== this.size) {
    throw new Error('Invalid length given for stateRelayPower LIFX packet');
  }

  obj = {};
  obj.relayIndex = buf.readUInt8LE(offset);
  offset += 1;
  obj.relayLevel = buf.readUInt16LE(offset);
  offset += 2;

  return obj;
};

/**
 * Converts the given packet specific object into a packet
 * @param  {Object} obj object with configuration data
 * @return {Buffer}     packet
 */
Packet.toBuffer = function (obj) {
  var buf = Buffer.alloc(this.size);
  buf.fill(0);
  var offset = 0;

  buf.readUInt8LE(obj.relayIndex, offset);
  offset += 1;
  buf.writeUInt16LE(obj.relayLevel, offset);
  offset += 2;

  return buf;
};

module.exports = Packet;

```
index.js Additions
```
/*
 * LIFX Switch device related packages
 */
packets.getRelayPower = require('./getRelayPower');
packets.setRelayPower = require('./setRelayPower');
packets.stateRelayPower = require('./stateRelayPower');

```

**Comment by ristomatti** [comment]
Well that was fast! :+1:. I've committed and pushed your changes to my work under branch `feature/switch-support` if someone is interested in following up or testing (given it requires some knowledge of the library internals).

Here's the change list:
https://github.com/node-lifx/lifx-lan-client/compare/master...ristomatti:feature/switch-support?expand=1

**Comment by ristomatti** [comment]
@Shakesbeard If the change list looks right, you can fix your repo by pulling the changes from my branch (unless you've got some other tweaks there as well of course).

**Comment by lebowski9000** [comment]
I'm happy to do testing in node-red as I have the device(s) installed. I may need some guidance on anything I need to update but happy to test.

**Comment by bkdfkup** [comment]
Hi all! Just getting back up to speed with progress and am grateful for the discussions that have occurred thus far. 

I too am in a position to test in Node-RED should an updated package be made available.

Cheers

**Comment by lebowski9000** [comment]
If it helps, I have this working with the HTTP version. It's only relay switch control. Much better vs using IFTTT

Just need the Lan version to match so I can get these off cloud control.

**Comment by bkdfkup** [comment]
Thanks for the suggestion, that is exactly what I am doing currently. Keen to remove dependency on internet wherever possible 👍

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lebowski9000** [comment]
Any joy with this?

**Comment by ristomatti** [comment]
> Any joy with this?

Sorry but no. To be able to test this on Node-RED would pretty much require to first add the feature to this module. Someone with the actual device would ideally first test that the packets kindly (but blindly) implemented from the spec by @Shakesbeard actually work.

This example script to test the `setWaveform` packet (https://github.com/node-lifx/lifx-lan-client/blob/master/example/setWaveform.js) could likely be used as a template to do that if you or someone else here feels adventurous. If so, the initial steps would be to:
1. Clone my fork mentioned on my previous message
2. Checkout the branch `switch-support`
3. Run `npm install` and then `npm run build`
4. Run the set waveform script using `node` to see if it will pulse the lights (to verify everything is setup correctly)
5. Modify the code that sets the packet

I'm currently too absorbed with work at the moment to get myself back to speed on how to do this exactly. I can try to help with issues doing the above if it doesn't sound overwhelming.

**Comment by ristomatti** [comment]
@lebowski9000 Any chance you haven't lost hope on this and would be able to help us by testing the changes proposed with #50? You should be able to install it from GitHub with:
```
npm install bradrees/lifx-lan-client#feature/switch-support
```

If yes, then please let us know the results by commenting on the pull request. Thanks!

**Comment by ristomatti** [comment]
@lebowski9000?
